DROP TABLE IF EXISTS users; 

CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email TEXT NOT NULL, 
    username TEXT NOT NULL, 
    password TEXT NOT NULL, 
    profile_img TEXT, 
    images json
); 

